### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Odonno** [MassivePixel/YAXL.Redux#2]
Thank you for your effort. This library and the other (like redux.NET) gave me the idea on how to make another Redux library for .NET using Reactive Extensions.

I recently made a project using react, redux, rxjs and redux-observable using typescript and this project gave me a lot of freedom and productivity in building a web app using Functional Reactive Programming model. I was considering making a similar thing for .NET because of the real opportunity we have to use C#/XAML (for WPF, XAML and Xamarin), Rx.NET and putting all of these code inside a .NET Standard library. ReduxSimple is based on the KISS principle reusing the best of FRP with 1. Reduce function is a pure function and 2. sync and async tasks are handled as observable.

For now, ReduxSimple is pretty stable in v1.2 with all desired features (dispatch/reduce/time travel). Next step is to take advantage of Redux in complex app with UI patterns/languages like XAML, making UI<->State communication a first-class citizen in the .NET world.

If you are interested, here the link to my library: https://github.com/Odonno/ReduxSimple

**Comment by tpetrina** [comment]
Cool library, will check out the implementation. I actually did not want to use Rx as a foundation block and wanted it to be an addon. Also, instead of using immutable structures I opted out for regular POCO classes and relied on developer being mindful when writing reducers.

**Comment by Odonno** [comment]
Me too. Using POCO classes is more convenient and consistent with .NET even though it can create side effects if you don't pay attention.

I mean, your implementation and mine are close and the main difference is Rx. I am also trying to bring even more good functional and reactive stuff like the upcoming versions of C# (immutability, nullable reference types) and the great library of @DavidArno https://github.com/DavidArno/SuccincT which brings `Option<T>` and pattern matching.
